- name: Login to GHCR
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Build image
  run: docker build -t ghcr.io/hasamuddinafz/portfolio-panel:latest .

- name: Push image
  run: docker push ghcr.io/hasamuddinafz/portfolio-panel:latest